version: '3.8'

services:
  player-app:
    image: player-app:latest
    container_name: player_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://player_db:5432/cicd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: player_db
    environment:
      POSTGRES_DB: cicd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02_data.sql

volumes:
  postgres_db:

